### ISSUE TITLE
Strange issues after update from 2.17.1 to 2.19.0

### ISSUE THREAD

**Issue by Tomasz-Silpion** [bluepayment-plugin/magento-2.x-plugin#4]
Seems that `BlueMedia_BluePayment::js/components.phtml` file declared in default.xml layout doesn't exists in template. That causes a mayor issue when the store is in production mode.

Additionally, not sure why in our store context with Smile_Elasticsuite installed product listing breaks the limit and display all category items maybe due to `CatalogWidgetProductsListPlugin` behaviour.

**Comment by zalazdi** [comment]
Package has been fixed in v2.19.1.

In case of Smile_Elasticsuite - I can suggest to create a custom package and overwrite plugin for `Magento\CatalogWidget\Block\Product\ProductsList` and set sort_order for Smile_Elasticsuite to eg. 10 and our
```xml
<plugin name="analytics_catalog_widget_product_list_plugin" type="BlueMedia\BluePayment\Plugin\CatalogWidgetProductsListPlugin" sortOrder="99" />
```

Plugin `analytics_catalog_widget_product_list_plugin` should be executed in the end.
